apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationsettests
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/andifg/applicaitonset.git
      revision: HEAD
      files:
      - path: "target/*.json"
  template:
    metadata:
      name: '{{.applicationName}}-guestbook'
      namespace: openshift-gitops
    spec:
      project: default
      source:
        chart: apache
        repoURL: registry-1.docker.io/bitnamicharts
        targetRevision: '{{.targetRevision}}'
        helm:
          releaseName: 'my-hello-{{.targetRevision}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default